---

#
# During package installation, a default HDB database is created in
# /var/lib/ldap with a "top" object named after the hostname of the
# node.  These tasks move this default database from /var/lib/ldap to
# a new location (`slapd_data_dir`).
#
# If AppArmor is installed, the corresponding profile will be
# replaced.
#

- name: Ensure data root exists
  when: slapd_data_root_dir is defined
  file: state=directory path="{{ slapd_data_root_dir }}" owner=root group=root mode=0755

- name: Check whether new data directory exists
  stat: path="{{ slapd_data_dir }}"
  register: slapd_new_data_dir
  
- name: Create new data directory
  when: slapd_new_data_dir.stat.exists == false
  file: state=directory path="{{ slapd_data_dir }}" owner="{{ slapd_user }}" group="{{ slapd_group }}" mode=0755 recurse=true
  register: slapd_created_new_data_dir

- name: Copy default database directory to new directory
  when: slapd_created_new_data_dir.changed
  shell: "cp -p -R {{ slapd_default_data_dir }}/* {{ slapd_data_dir }}"

- name: Check whether AppArmor restricts slapd
  stat: path="{{ slapd_apparmor_dir }}/{{slapd_apparmor_name }}"
  register: slapd_apparmor
  tags: [apparmor]

- name: Tell AppArmor to allow slapd to access new directory
  when: slapd_apparmor.stat.exists
  template: src=templates/apparmor.j2 dest="{{ slapd_apparmor_dir }}/local/{{ slapd_apparmor_name }}" owner=root group=root mode=0644
  register: slapd_apparmor_override
  tags: [apparmor]

- name: Copy default config database to new directory
  when: slapd_apparmor_override.changed
  command: "apparmor_parser -r {{ slapd_apparmor_dir }}/{{ slapd_apparmor_name }}"
  tags: [apparmor]

- name: Set data directory via LDAP
  ldap_attr:
    dn:     "olcDatabase={1}hdb,cn=config"
    name:   olcDbDirectory
    values: "{{ slapd_data_dir }}"
    state:  exact
